/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-06-09 01:15:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.lounge;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.dw.member.vo.MemberVO;
import kr.or.dw.lounge.vo.ReplyVO;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import kr.or.dw.util.BuildSqlMapClient;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.util.List;
import kr.or.dw.lounge.vo.LoungeVO;
import kr.or.dw.ranking.vo.GameVO;
import kr.or.dw.lounge.vo.LoungeVO;

public final class game_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/lounge/_tail.jsp", Long.valueOf(1686214438053L));
    _jspx_dependants.put("/WEB-INF/view/lounge/../gnb.jsp", Long.valueOf(1686271655473L));
    _jspx_dependants.put("/WEB-INF/view/lounge/_head.jsp", Long.valueOf(1686209321264L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.dw.lounge.vo.LoungeVO");
    _jspx_imports_classes.add("kr.or.dw.member.vo.MemberVO");
    _jspx_imports_classes.add("com.ibatis.sqlmap.client.SqlMapClient");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("kr.or.dw.ranking.vo.GameVO");
    _jspx_imports_classes.add("kr.or.dw.lounge.vo.ReplyVO");
    _jspx_imports_classes.add("kr.or.dw.util.BuildSqlMapClient");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print( request.getContextPath());
      out.write("/img/redapp_ico16.png\" type=\"image/x-icon\" sizes=\"16x16\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print( request.getContextPath());
      out.write("/img/redapp_ico32.png\" type=\"image/x-icon\" sizes=\"32x32\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>RedApp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/game.css\">\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/all.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function () {\r\n");
      out.write("	$('#join').on('click', function () {\r\n");
      out.write("		alert('가입 되었습니다.');\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#unJoin').on('click', function () {\r\n");
      out.write("		alert('가입 해제 되었습니다.');\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/gnb.css\">\r\n");
      out.write("<!-- 글로벌 네비게이션 바 부분 -->\r\n");
      out.write("<header class=\"gnb\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"logo\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/main.do\"><img src=\"../img/gnb_redapp_logo_v2.png\"></a></div>\r\n");
      out.write("        <div class=\"gnbBarLeft\">\r\n");
      out.write("            <div class=\"gnbAllmenu\">\r\n");
      out.write("                 <a href=\"#gnbAllLayer\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#gnbAllLayer\" aria-controls=\"gnbAllLayer\">\r\n");
      out.write("                    <span class=\"gnbIcon\"></span><span class=\"text\">메뉴</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"gnbBarRight\">\r\n");
      out.write("            <div class=\"member-info\">\r\n");
      out.write("                ");

                	Object user_no = session.getAttribute("user_no");
                	Object auth_cd = session.getAttribute("auth_cd");
                	if(user_no != null){
                
      out.write("\r\n");
      out.write("                <a class=\"btn btn-basic\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">로그아웃</a>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <a class=\"btn btn-basic\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/loginForm.do\">로그인</a>\r\n");
      out.write("         		");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"offcanvas offcanvas-start gnbAllLayer\" data-bs-scroll=\"true\" tabindex=\"-1\" id=\"gnbAllLayer\" aria-labelledby=\"gnbAllLayerLabel\">\r\n");
      out.write("    <div class=\"gnbTitle\">\r\n");
      out.write("        <h2>Global Navigation Bar</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbLayerBt\">\r\n");
      out.write("        <a href=\"#\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\">\r\n");
      out.write("            <span class=\"gnbIcon\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbMyLayer\">\r\n");
      out.write("        <div class=\"gnbList\">\r\n");
      out.write("            <div class=\"gnbCell\">\r\n");
      out.write("                <h3><a href=\"");
      out.print( request.getContextPath());
      out.write("/main.do\">HOME <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <h3><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=3\">게임 라운지 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=1\">다운랭킹</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=2\">구독랭킹</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"gnbCell\">\r\n");
      out.write("                <h3><a href=\"https://news.kmib.co.kr/article/list.asp?sid1=spo&sid2=0012\">e스포츠 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <h3><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\">고객센터 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:alert('개발 준비중 입니다.','self_close');\">사이트소개</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/faq.do\">자주묻는질문</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbListService\">\r\n");
      out.write("        <h2 class=\"d-none\">서비스</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/myinfo.do\"><span></span>내정보</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\"><span></span>고객센터</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\"><span></span>공지사항</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/faq.do\"><span></span>자주묻는질문</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a class=\"gnbBtAll\" href=\"");
      out.print( request.getContextPath());
      out.write("/customer/sitemap.do\">전체서비스</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');

	int g_user = 0;
	if(request.getAttribute("g_user") != null){
		g_user = (int)request.getAttribute("g_user");	
	}
	GameVO gameVo = (GameVO) request.getAttribute("gameVo");
	List<LoungeVO> loungeList = (List<LoungeVO>) request.getAttribute("loungeList");
	List<LoungeVO> allLoungeList = (List<LoungeVO>) request.getAttribute("allLoungeList");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(function () {\r\n");
      out.write("		$('#downBtn').on('click', function () {\r\n");
      out.write("			");
 
				SqlMapClient client = BuildSqlMapClient.getSqlMapClient();
			    int N = gameVo.getG_no();
				client.update("lounge.increaseDown", N);
			
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 게임 커뮤니티 헤더 부분-->\r\n");
      out.write("<div class=\"game-intro\" style=\"background-image: url('/imgPath/");
      out.print( gameVo.getG_no());
      out.write("-background.jpg'); background-position-y: 30%;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header-container\">\r\n");
      out.write("            <div class=\"header-icon\">\r\n");
      out.write("                <img src=\"/imgPath/");
      out.print( gameVo.getG_no());
      out.write("-icon.png\" class=\"app-icon\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-data\">\r\n");
      out.write("                <h2 class=\"header-title\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/gameLounge.do?g_no=");
      out.print( gameVo.getG_no());
      out.write('"');
      out.write('>');
      out.print( gameVo.getG_name());
      out.write("</a></h2>\r\n");
      out.write("                <p class=\"header-sub\">");
      out.print( gameVo.getG_com());
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-button\">\r\n");
      out.write("                <a id=\"downBtn\" class=\"btn btn-download\" href=\"https://play.google.com/store/apps/details?id=");
      out.print(gameVo.getG_url());
      out.write("\">다운로드</a>\r\n");
      out.write("                ");
if (g_user != (int)session.getAttribute("user_no")) {
      out.write("\r\n");
      out.write("                <a class=\"btn btn-join\" href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/joinLounge.do?g_no=");
      out.print( gameVo.getG_no());
      out.write("\" id=\"join\">가입하기</a>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <a class=\"btn btn-join\" href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/unJoinLounge.do?g_no=");
      out.print( gameVo.getG_no());
      out.write("\" id=\"unJoin\">가입해제</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"header-footer\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 게임 커뮤니티 컨텐츠 내용 부분 -->\r\n");
      out.write("<div class=\"game-wrapper\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"content\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/notice.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".latest-all .latest-all-title {\r\n");
      out.write("   border-bottom: 2px solid #a7a7a7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".latest-all .latest-all-title .title-main {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: auto;\r\n");
      out.write("   font-size: 1.35rem;\r\n");
      out.write("   font-weight: 700;\r\n");
      out.write("   border-bottom: 2px solid #333;\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".latest-all .latest-all-title .title-more {\r\n");
      out.write("   margin-top: 10px;\r\n");
      out.write("   margin-right: 10px;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   color: #333;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

   LoungeVO loungeVo = (LoungeVO) request.getAttribute("loungeVo");
   List<ReplyVO> replyList = (List<ReplyVO>)request.getAttribute("replyList");
   DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
   
   int userLike = 0;
   if(request.getAttribute("userLike") != null){
      userLike = Integer.parseInt(request.getAttribute("userLike").toString());
   }

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("      \r\n");
      out.write("      function replyTemplate(reply){\r\n");
      out.write("         \r\n");
      out.write("         $('#re_container').prepend(\r\n");
      out.write("           '<div class=\"list\">'   \r\n");
      out.write("                 +'   <span class=\"nickname\">'\r\n");
      out.write("                 +'      <a href=\"#\">' + reply.nick + '</a>'\r\n");
      out.write("                 +'   </span>'\r\n");
      out.write("                 +'   <span class=\"time\">' + reply.re_wdt + '</span>'\r\n");
      out.write("                 +'   <div class=\"commcont\">' + reply.re_content + '</div>'\r\n");
      out.write("                 +' </div>'\r\n");
      out.write("         );\r\n");
      out.write("      };\r\n");
      out.write("      \r\n");
      out.write("      $('#re_form').on('submit', function(e){\r\n");
      out.write("         e.preventDefault();\r\n");
      out.write("         console.log(\"");
      out.print( gameVo.getG_no());
      out.write("\");\r\n");
      out.write("         let re_content = $('#re_form').find('#textbox').val();\r\n");
      out.write("         let bd_no = \"");
      out.print(loungeVo.getBd_no());
      out.write("\";\r\n");
      out.write("         \r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"");
      out.print(request.getContextPath());
      out.write("/lounge/reply.do\",\r\n");
      out.write("            dataType : \"json\",\r\n");
      out.write("            method : \"post\",\r\n");
      out.write("            data : {\r\n");
      out.write("               \"bd_no\" : bd_no,\r\n");
      out.write("               \"re_content\" : re_content,\r\n");
      out.write("               \"g_no\" : ");
      out.print( gameVo.getG_no());
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            success : function(res){\r\n");
      out.write("               console.log(res);\r\n");
      out.write("               replyTemplate(res.reply);\r\n");
      out.write("            },\r\n");
      out.write("            error : function(){\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("         $('#re_form').find('#textbox').val(\"\");\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("     // 좋아요 손가락 색상 변경 함수\r\n");
      out.write("      function changeLikeColor(){\r\n");
      out.write("         let l = $('#likeBtn');   // 좋아요 'a' 태그 요소 가져오기\r\n");
      out.write("         let flag = l.data('like');   // 가져온 'a' 태그의 data-like 속성값 확인\r\n");
      out.write("         if(flag){   // data-like 값으로 분개\r\n");
      out.write("            // 좋아요 눌려있을 때\r\n");
      out.write("            l.data('like', false);\r\n");
      out.write("            $(\"#likeBtn\").css(\"color\",\"#ce330e\");\r\n");
      out.write("         }else{\r\n");
      out.write("            // 좋아요를 안눌려있을 때\r\n");
      out.write("            l.data('like', true);\r\n");
      out.write("            $(\"#likeBtn\").css(\"color\",\"#333\");\r\n");
      out.write("         };\r\n");
      out.write("         \r\n");
      out.write("         return flag;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      changeLikeColor();   // 페이지 최초 로딩시 좋아요 색상 변경하기 위해 호출\r\n");
      out.write("      \r\n");
      out.write("      // 좋아요\r\n");
      out.write("      $('#likeBtn').on('click', function(){\r\n");
      out.write("         if(");
      out.print(session.getAttribute("user_no") == null);
      out.write(")   return; // 로그인을 했을 때만 이벤트 로직 수행\r\n");
      out.write("         let flag = changeLikeColor();\r\n");
      out.write("         \r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"");
      out.print(request.getContextPath());
      out.write("/lounge/like.do\",\r\n");
      out.write("            dataType : \"json\",\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {\r\n");
      out.write("               bd_no : \"");
      out.print(loungeVo.getBd_no());
      out.write("\",\r\n");
      out.write("               likeFlag : flag,\r\n");
      out.write("               g_no : \"");
      out.print( gameVo.getG_no());
      out.write("\"\r\n");
      out.write("            },\r\n");
      out.write("            success : function(res){\r\n");
      out.write("               console.log(res);\r\n");
      out.write("               $('#likeCnt').text('(' + res.count + ')');\r\n");
      out.write("            },\r\n");
      out.write("            error : function(err){\r\n");
      out.write("               alert(err.status);\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("      $('#textBox').keyup(function (e) {\r\n");
      out.write("         let content = $(this).val();\r\n");
      out.write("          \r\n");
      out.write("          // 글자수 세기\r\n");
      out.write("          if (content.length == 0 || content == '') {\r\n");
      out.write("             $('#count').text('0');\r\n");
      out.write("          } else {\r\n");
      out.write("             $('#count').text(content.length);\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          // 글자수 제한\r\n");
      out.write("          if (content.length > 200) {\r\n");
      out.write("             // 200자 부터는 타이핑 되지 않도록\r\n");
      out.write("              $(this).val($(this).val().substring(0, 200));\r\n");
      out.write("              // 200자 넘으면 알림창 뜨도록\r\n");
      out.write("              alert('글자수는 200자까지 입력 가능합니다.');\r\n");
      out.write("          };\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"notice-wrapper\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"board-view\">\r\n");
      out.write("         <div class=\"phead\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("               ");
      out.print(loungeVo.getBd_title());
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right\">\r\n");
      out.write("               <span class=\"nick\">");
      out.print(loungeVo.getNick());
      out.write("</span>\r\n");
      out.write("               <span class=\"date\"><i class=\"bi bi-clock\"></i> ");
      out.print(loungeVo.getBd_wdt());
      out.write("</span>\r\n");
      out.write("               <span class=\"like\"><i class=\"bi bi-heart\"></i> ");
      out.print( loungeVo.getBd_like() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"pbody\">\r\n");
      out.write("            <div class=\"ck-content\">\r\n");
      out.write("               <p>");
      out.print(loungeVo.getBd_content());
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <style>\r\n");
      out.write("         .board-view {\r\n");
      out.write("          padding: 0;\r\n");
      out.write("          background: #fff;\r\n");
      out.write("          border-radius: 0;\r\n");
      out.write("          -webkit-box-shadow: none;\r\n");
      out.write("          box-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("         .board-view .nick,\r\n");
      out.write("         .board-view .date,\r\n");
      out.write("         .board-view .like {\r\n");
      out.write("          font-size: 0.90rem;\r\n");
      out.write("          font-weight: 300;\r\n");
      out.write("          margin-left: 5px;\r\n");
      out.write("          color: #909090;\r\n");
      out.write("         }\r\n");
      out.write("         .board-view .nick {\r\n");
      out.write("          color: #333;\r\n");
      out.write("          font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("         .board-view .btnArea .like:hover,\r\n");
      out.write("         .board-view .btnArea .like {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: 2px solid #e6e6e6;\r\n");
      out.write("          border-radius: 50%;\r\n");
      out.write("          width: 48px;\r\n");
      out.write("          height: 48px;\r\n");
      out.write("         }\r\n");
      out.write("         .board-view .btnArea .like a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 3px 0 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 1.65rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("         }\r\n");
      out.write("         </style>\r\n");
      out.write("         <div class=\"btnArea\">\r\n");
      out.write("            <div class=\"like\"><a href=\"#\" id=\"likeBtn\" data-like=");
      out.print(userLike == 1 ? true : false );
      out.write("><i class=\"bi bi-heart-fill\"></i></a></div>\r\n");
      out.write("            <div class=\"sns\">\r\n");
      out.write("               <ul class=\"clearfix\">\r\n");
      out.write("                  <li class=\"link\"><a href=\"#\" onclick=\"return false;\"\r\n");
      out.write("                     data-clipboard-text=\"localhost/lounge/boardView.do?n_no=");
      out.print(loungeVo.getBd_no());
      out.write("\"\r\n");
      out.write("                     class=\"btnUrlCopyToClipboard\">주소복사</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"btmBtns\">\r\n");
      out.write("            <ul class=\"clearfix\">\r\n");
      out.write("               <li class=\"list\">\r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/gameLounge.do?bd_no=");
      out.print( loungeVo.getBd_no());
      out.write("&g_no=");
      out.print( gameVo.getG_no());
      out.write("\">목록</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li class=\"list\">\r\n");
      out.write("               ");
if (session.getAttribute("user_no") != null && session.getAttribute("user_no").equals(loungeVo.getUser_no())) { 
      out.write("\r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/write.do?g_no=");
      out.print( gameVo.getG_no());
      out.write("&bd_no=");
      out.print( loungeVo.getBd_no());
      out.write("\">수정</a>\r\n");
      out.write("               ");
} 
      out.write("\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <style>\r\n");
      out.write("            .bottom_txar_wrap {\r\n");
      out.write("             height: 170px;\r\n");
      out.write("             background-color: #e8eaee;\r\n");
      out.write("             border: 1px solid #dcdde1;\r\n");
      out.write("         }\r\n");
      out.write("            .bottom_txar_wrap .txar {\r\n");
      out.write("             float: left;\r\n");
      out.write("             padding: 20px;\r\n");
      out.write("             width: calc(100% - 20px);\r\n");
      out.write("             height: 90px;\r\n");
      out.write("             margin-top: 10px;\r\n");
      out.write("             margin-left: 10px;\r\n");
      out.write("             background-color: #fff;\r\n");
      out.write("             resize: none;\r\n");
      out.write("             overflow: hidden;\r\n");
      out.write("             overflow-y: auto;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn {\r\n");
      out.write("             position: relative;\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-top: 11px;\r\n");
      out.write("             width: 100%;\r\n");
      out.write("             height: 42px;\r\n");
      out.write("             line-height: 42px;\r\n");
      out.write("             padding: 0 10px;\r\n");
      out.write("         }\r\n");
      out.write("         .glist_number {\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-right: 20px;\r\n");
      out.write("             font-size: 14px !important;\r\n");
      out.write("             color: #666666;\r\n");
      out.write("             margin-right: 10px;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn span {\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-right: 0px;\r\n");
      out.write("             font-size: 12px;\r\n");
      out.write("             color: #666666;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn span .btn-write {\r\n");
      out.write("             width: 100%;\r\n");
      out.write("             background: #d63338;\r\n");
      out.write("             color: #fff;\r\n");
      out.write("             padding: 7px 5px;\r\n");
      out.write("             border-radius: 0;\r\n");
      out.write("         }\r\n");
      out.write("            </style>\r\n");
      out.write("            <div class=\"bottom_txar_wrap\" style=\"\">\r\n");
      out.write("             <form id=\"re_form\">\r\n");
      out.write("             <textarea id=\"textbox\" name=\"comment\" cols=\"30\" rows=\"10\" class=\"txar\" placeholder=\"댓글을 입력하세요.\"></textarea>\r\n");
      out.write("             <div class=\"bottom_txar_btn\">\r\n");
      out.write("                 <div class=\"float-end text-end\">\r\n");
      out.write("                     <div class=\"glist_number\">(<em id=\"count\">0</em>/200)</div>\r\n");
      out.write("                     <span><button type=\"submit\" class=\"btn btn-write\" >댓글등록</button></span>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </div>\r\n");
      out.write("            </form>   \r\n");
      out.write("         </div>\r\n");
      out.write("            <style>\r\n");
      out.write("            .comment {\r\n");
      out.write("               width: 100%;\r\n");
      out.write("               padding: 15px 0;\r\n");
      out.write("               border-top: 2px solid #333;\r\n");
      out.write("            }\r\n");
      out.write("            .comment a {\r\n");
      out.write("               text-decoration: none;\r\n");
      out.write("               color: #333;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list {\r\n");
      out.write("               padding:15px 0;\r\n");
      out.write("               border-bottom: 1px solid #eee;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .nickname {\r\n");
      out.write("               font-size:1.05rem;\r\n");
      out.write("               font-weight: 700;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .time {\r\n");
      out.write("               font-size:0.95rem;\r\n");
      out.write("               font-weight: normal;\r\n");
      out.write("               margin-left: 5px;\r\n");
      out.write("               letter-spacing: -0.05em;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .commcont {\r\n");
      out.write("               margin: 5px 0 0;\r\n");
      out.write("               font-size: 0.85rem;\r\n");
      out.write("            }\r\n");
      out.write("            </style>\r\n");
      out.write("            <div class=\"comment\" id=\"re_container\">\r\n");
      out.write("            ");

               if(replyList != null) {
                  for(ReplyVO replyVo : replyList){
            
      out.write("\r\n");
      out.write("               <div class=\"list\">   \r\n");
      out.write("                  <span class=\"nickname\">\r\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/userInfo.do?user_no=");
      out.print( replyVo.getUser_no());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( replyVo.getNick() );
      out.write(" </a>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"time\"> ");
      out.print( formatter.format(replyVo.getRe_wdt()));
      out.write(" </span>\r\n");
      out.write("                  <div class=\"commcont\">");
      out.print( replyVo.getRe_content() );
      out.write("</div>\r\n");
      out.write("               </div>\r\n");
      out.write("            ");

                  }
               }
            
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("                <!-- 사이드 메뉴 부분 -->\r\n");
      out.write("                <div class=\"side-menu\">\r\n");
      out.write("                	");
if (session.getAttribute("user_no") != null) { 
      out.write("\r\n");
      out.write("                    <a class=\"btn btn-write\" href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/write.do?g_no=");
      out.print( gameVo.getG_no());
      out.write("\">글쓰기</a>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    <div class=\"game-search\">\r\n");
      out.write("                        <div class=\"SearchForm\" data-style-type=\"LIGHT\">\r\n");
      out.write("                            <form class=\"Form\" action=\"");
      out.print( request.getContextPath());
      out.write("/lounge/search.do\">\r\n");
      out.write("                            <input class=\"searchInput\" type=\"text\" placeholder=\"커뮤니티 게시물 검색\" name=\"searchL\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"g_no\" value=\"");
      out.print( gameVo.getG_no());
      out.write("\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btnSearch\">검색하기</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      	<div class=\"sidebar\">\r\n");
      out.write("                            <small class=\"text-muted pl-3\"><a href=\"#\">전체 게시글</a></small>\r\n");
      out.write("                            <ul class=\"my-3\">\r\n");
      out.write("                            	");

                            		for (LoungeVO lounge : allLoungeList) {
                            	
      out.write("\r\n");
      out.write("                            	<ui>\r\n");
      out.write("                            		<a href=\"");
      out.print( request.getContextPath());
      out.write("/lounge/boardView.do?bd_no=");
      out.print( lounge.getBd_no());
      out.write("&g_no=");
      out.print( lounge.getG_no());
      out.write('"');
      out.write('>');
      out.print( lounge.getBd_title() );
      out.write("</a>\r\n");
      out.write("                            	</ui><br>\r\n");
      out.write("                            	");

                            		}
                            	
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 하단 풋터 부분 -->\r\n");
      out.write("                <div class=\"footer\">\r\n");
      out.write("                    <cite>RedApp Korea ⓒ 2023</cite>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
