/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-08-11 01:08:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class open_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686551956753L));
    _jspx_dependants.put("jar:file:/C:/dwFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EazyRP_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.104.2\">\r\n");
      out.write("  <title>EazyRP</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS only -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"theme-color\" content=\"#712cf9\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/bootstrap/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/*   html { */\r\n");
      out.write("/*     height: 100%; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   body { */\r\n");
      out.write("/*     overflow-x: hidden; */\r\n");
      out.write("/*     height: 100%; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .a:hover { */\r\n");
      out.write("/*     background-color: darkslategray; */\r\n");
      out.write("/*     transition-duration: 0.35s; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .nav--link.show { */\r\n");
      out.write("/*     color: #fff !important; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .dropdown-menu { */\r\n");
      out.write("/*     border: 1px solid #eee; */\r\n");
      out.write("/*     border-radius: 0; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .card { */\r\n");
      out.write("/*     border: solid 6px #f8f9fa; */\r\n");
      out.write("/*     border-radius: 10px; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   /* Custom styles */ */\r\n");
      out.write("/*   .navbar { */\r\n");
      out.write("/*     background-color: #7bc4b2; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .navbar-brand { */\r\n");
      out.write("/*     color: #fff; */\r\n");
      out.write("/*     font-weight: bold; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .nav-link { */\r\n");
      out.write("/*     color: #fff; */\r\n");
      out.write("/*     text-decoration: none; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .nav-link:hover { */\r\n");
      out.write("/*     color: #fff; */\r\n");
      out.write("/*     background-color: #6ea89d; */\r\n");
      out.write("/*     transition-duration: 0.35s; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .dropdown-menu { */\r\n");
      out.write("/*     background-color: #7bc4b2; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .dropdown-item { */\r\n");
      out.write("/*     color: #fff; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .dropdown-item:hover { */\r\n");
      out.write("/*     background-color: #6ea89d; */\r\n");
      out.write("/*     transition-duration: 0.35s; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .card-header { */\r\n");
      out.write("/*     background-color: #f8f9fa; */\r\n");
      out.write("/*     color: #000; */\r\n");
      out.write("/*     font-weight: bold; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("/*   .table { */\r\n");
      out.write("/*     color: #000; */\r\n");
      out.write("/*   } */\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
