/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-08-17 06:41:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Eazy ERP 로그인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("html {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Varela Round', sans-serif;\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".modal-login {\r\n");
      out.write("	width: 350px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".modal-login .modal-content {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .modal-header {\r\n");
      out.write("	border-bottom: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .close {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: -10px;\r\n");
      out.write("	right: -10px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login h4 {\r\n");
      out.write("	color: #636363;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .modal-content {\r\n");
      out.write("	color: #999;\r\n");
      out.write("	border-radius: 1px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	border: 1px solid #f3f3f3;\r\n");
      out.write("	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("	padding: 25px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .form-group {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login label {\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .form-control {\r\n");
      out.write("	min-height: 38px;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("	box-shadow: none !important;\r\n");
      out.write("	border-width: 0 0 1px 0;\r\n");
      out.write("	border-radius: 0;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .form-control:focus {\r\n");
      out.write("	border-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .input-group-addon {\r\n");
      out.write("	max-width: 42px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background: none;\r\n");
      out.write("	border-bottom: 1px solid #ced4da;\r\n");
      out.write("	padding-right: 5px;\r\n");
      out.write("	border-radius: 0;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .btn, .modal-login .btn:active {        \r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	background: #4685e4 !important;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	min-width: 140px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .btn:hover, .modal-login .btn:focus {\r\n");
      out.write("	background: #4685e4 !important;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .hint-text {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .modal-footer {\r\n");
      out.write("	color: #999;\r\n");
      out.write("	border-color: #dee4e7;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 0 -25px -25px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".modal-login a {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".modal-login a:hover {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".modal-login a {\r\n");
      out.write("	color: #636363;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}	\r\n");
      out.write(".modal-login a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".modal-login .fa {\r\n");
      out.write("	font-size: 21px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 6px;\r\n");
      out.write("}\r\n");
      out.write(".trigger-btn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 100px auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Modal HTML -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal-dialog modal-login \">\r\n");
      out.write("		<div class=\"modal-content \">\r\n");
      out.write("			<div class=\"modal-header\">	\r\n");
      out.write("				<div>\r\n");
      out.write("				<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/EazyRP2.png\" style=\"width: 100px;\">\r\n");
      out.write("				</div>	\r\n");
      out.write("				<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\">\r\n");
      out.write("				<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/common/login.do\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\" name=\"id\" placeholder=\"아이디\" required=\"required\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" name=\"pwd\" placeholder=\"패스워드\" required=\"required\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-info btn-block btn-sm\" id=\"loginBtn\">로그인</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-info btn-block btn-sm\" id=\"regiser\" >회원가입</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<p class=\"hint-text text-info\"><a href=\"#\" id=\"idfind\">아이디 </a> / <a href=\"#\" id=\"pwfind\">비밀번호찾기</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>    \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("	$('#regiser').on('click', function(){\r\n");
      out.write("		location.href = \"");
      out.print(request.getContextPath());
      out.write("/common/registerForm.do\"; \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#pwfind').on('click', function(){\r\n");
      out.write("		location.href = \"");
      out.print(request.getContextPath());
      out.write("/member/PWfindForm.do\"; \r\n");
      out.write("	});\r\n");
      out.write("	$('#idfind').on('click', function(){\r\n");
      out.write("		location.href = \"");
      out.print(request.getContextPath());
      out.write("/member/IDfindForm.do\"; \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
