/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-08-17 05:39:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/../include/footer_js.jsp", Long.valueOf(1692250377172L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    html, body{\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .bd-placeholder-img {\r\n");
      out.write("      font-size: 1.125rem;\r\n");
      out.write("      text-anchor: middle;\r\n");
      out.write("      -webkit-user-select: none;\r\n");
      out.write("      -moz-user-select: none;\r\n");
      out.write("      user-select: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (min-width: 768px) {\r\n");
      out.write("      .bd-placeholder-img-lg {\r\n");
      out.write("        font-size: 3.5rem;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .b-example-divider {\r\n");
      out.write("      height: 3rem;\r\n");
      out.write("      background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("      border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("      border-width: 1px 0;\r\n");
      out.write("      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .b-example-vr {\r\n");
      out.write("      flex-shrink: 0;\r\n");
      out.write("      width: 1.5rem;\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .bi {\r\n");
      out.write("      vertical-align: -.125em;\r\n");
      out.write("      fill: currentColor;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .p-2 {\r\n");
      out.write("      color: whitesmoke;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav d-flex {\r\n");
      out.write("      justify-content: space-evenly;\r\n");
      out.write("    } */\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- main -->\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("     <!-- 11111 -->\r\n");
      out.write("     <div class=\"h-60 col-lg-8 container text-center;\" style=\"align-items: center; display: flex; justify-content: center;\">\r\n");
      out.write("\r\n");
      out.write("      <!-- .card -->\r\n");
      out.write("      <div class=\"card card-fluid\" style=\"width: 80%;\">\r\n");
      out.write("        <div class=\"card-body\" style=\"text-align: center;\">\r\n");
      out.write("          <!-- form -->\r\n");
      out.write("          <div class=\"d-flex align-items-center pb-3 mb-3 text-center link-dark text-decoration-none border-bottom\">\r\n");
      out.write("            <span class=\"fs-5 fw-semibold \"> 개인정보 조회 </span>\r\n");
      out.write("            <form id=\"searchForm2\" method=\"post\"\r\n");
      out.write("							action=\"/member/mypage.do?mcode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mcode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("							style=\"display: contents;\"></form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- .form-group -->\r\n");
      out.write("          <form action=\"/member/userProfile.do\" method=\"post\" style=\"text-align: -webkit-center; width: 100%;align-items: center; display: inline-block;\">\r\n");
      out.write("            <div class=\"mb-8 row\"  style=\"align-items: center; justify-content: center;\">\r\n");
      out.write("              <label for=\"staticid\" class=\"col-sm-2 col-form-label\">아이디</label>\r\n");
      out.write("              <div class=\"col-sm-8\">\r\n");
      out.write("                <input type=\"id\" readonly class=\"form-control-plaintext\" id=\"staticid\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-8 row\" style=\"align-items: center; justify-content: center;\" >\r\n");
      out.write("              <label for=\"staticname\" class=\"col-sm-2 col-form-label\">이 름</label>\r\n");
      out.write("              <div class=\"col-sm-8\">\r\n");
      out.write("                <input type=\"name\" readonly class=\"form-control-plaintext\" id=\"staticname\" name=\"name\"value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-8 row\" style=\"align-items: center; justify-content: center;\" >\r\n");
      out.write("              <label for=\"staticphone\" class=\"col-sm-2 col-form-label\">연락처</label>\r\n");
      out.write("              <div class=\"col-sm-8\">\r\n");
      out.write("                <input type=\"phone\" readonly class=\"form-control-plaintext\" id=\"staticphone\" name=\"tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-8 row\" style=\"align-items: center; justify-content: center;\" > \r\n");
      out.write("              <label for=\"staticadd\" class=\"col-sm-2 col-form-label\">집주소</label>\r\n");
      out.write("              <div class=\"col-sm-8\">\r\n");
      out.write("                <input type=\"add\" readonly class=\"form-control-plaintext\" id=\"addr\" name=\"addr\"value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.addr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-8 row\" style=\"align-items: center; justify-content: center;\">\r\n");
      out.write("              <label for=\"staticEmail\" class=\"col-sm-2 col-form-label\">이메일</label>\r\n");
      out.write("              <div class=\"col-sm-8\">\r\n");
      out.write("                <input type=\"emailstaticadd\" readonly class=\"form-control-plaintext\" id=\"Email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div><!-- /.form-group -->\r\n");
      out.write("          </form><!-- /form -->\r\n");
      out.write(" \r\n");
      out.write("            <div class=\"btn\" style=\"border:0\">\r\n");
      out.write("              <button type=\"submit\" id=\"repwdBtn\" class=\"btn btn-primary \" >비밀번호 변경</button>\r\n");
      out.write("              <button type=\"submit\" id=\"modifyBtn\" class=\"btn btn-primary\" >정보변경</button>\r\n");
      out.write("              <button type=\"submit\" id=\"deleteBtn\" class=\"btn btn-primary\" >회원탈퇴</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- /.card-body -->\r\n");
      out.write("      </div><!-- /.card -->\r\n");
      out.write("    </div>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("  </html>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("	$('#repwdBtn').on('click', function(){\r\n");
      out.write("		location.href = \"/member/repwdForm.do?mcode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mcode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#modifyBtn').on('click', function(){\r\n");
      out.write("		location.href = \"/member/modProfileForm.do?mcode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mcode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#deleteBtn').on('click', function(){\r\n");
      out.write("		if(confirm(\"정말 탈퇴하시겠습니까\")){\r\n");
      out.write("		location.href=\"/member/delete.do\"	\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/bootstrap/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	function goPage(murl, mcode, micon){\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		if(murl.indexOf('?') != -1) {\r\n");
      out.write("			let modMurl = murl.substring(0, murl.indexOf('?'));	\r\n");
      out.write("			sessionStorage.setItem(\"murl\", murl);		\r\n");
      out.write("		}else {\r\n");
      out.write("			sessionStorage.setItem(\"murl\", murl);		\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		sessionStorage.setItem(\"mcode\", mcode);\r\n");
      out.write("		sessionStorage.setItem(\"micon\", micon);\r\n");
      out.write("		\r\n");
      out.write("		let modMcode = mcode.substring(0,3) + \"0000\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		location.href = \"");
      out.print( request.getContextPath() );
      out.write("\" + murl + \"?mcode=\" + modMcode + \"&murl=\" + murl;\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
