/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2023-05-26 05:54:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>RedApp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://moku.store/css/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css?<?php echo time() ?>\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("// 자바스크립트 & 제이쿼리에서 사용하는 데이터 정보 함수\r\n");
      out.write("var is_member = '<?php echo isset($is_member)?$is_member:''; ?>';\r\n");
      out.write("var is_admin  = '<?php echo isset($is_admin)?$is_admin:''; ?>';\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"navbar navbar-expand-lg header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"index.jsp\">\r\n");
      out.write("                <h2>RedApp</h2>\r\n");
      out.write("                <p>앱게임 커뮤니티</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"m-gnb\">\r\n");
      out.write("            <?php\r\n");
      out.write("                if ($is_member) {\r\n");
      out.write("            ?>\r\n");
      out.write("            <a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("            <?php\r\n");
      out.write("                    if ($is_admin) {\r\n");
      out.write("            ?>\r\n");
      out.write("            <a href=\"./admin/\" class=\"admin\"><i class=\"bi bi-gear-fill\"></i></a>\r\n");
      out.write("            <?php } ?>\r\n");
      out.write("            <a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("            <?php } else { ?>\r\n");
      out.write("            <a href=\"login.jsp\">로그인</a>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/joinForm.do\">회원가입</a>\r\n");
      out.write("            <?php } ?>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"menu-toggle d-lg-none\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li></li>\r\n");
      out.write("                <li></li>\r\n");
      out.write("                <li></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarScroll\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"/redapp/\" class=\"nav-link\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"game.jsp\" class=\"nav-link\">커뮤니티</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">종합랭킹 <!-- 사용안함 div class=\"sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div--></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"ranking/\">인기 랭킹</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"ranking/\">가입 랭킹</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"ranking/user.jsp\">회원 랭킹</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"\" class=\"nav-link\">e스포츠</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">고객센터 <!-- 사용안함 div class=\"sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div--></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"\">사이트소개</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"\">자주묻는질문</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                <li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"col-md-3 text-end member-info\">\r\n");
      out.write("                <?php\r\n");
      out.write("                    if ($is_member) {\r\n");
      out.write("                ?>\r\n");
      out.write("                <a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("                <?php\r\n");
      out.write("                        if ($is_admin) {\r\n");
      out.write("                ?>\r\n");
      out.write("                <a href=\"./admin/\" class=\"admin\"><i class=\"bi bi-gear-fill\"></i></a>\r\n");
      out.write("                <?php } ?>\r\n");
      out.write("                <a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("                <?php } else { ?>\r\n");
      out.write("                <a href=\"login.jsp\">로그인</a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/joinForm.do\">회원가입</a>\r\n");
      out.write("                <?php } ?>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"gnb-m\">\r\n");
      out.write("                <div class=\"nav accordion\" id=\"accordionSidenav\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"\">\r\n");
      out.write("                        Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"nav-link\" href=\"game.jsp\">\r\n");
      out.write("                        커뮤니티\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"javascript:void(0);\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse1\" aria-expanded=\"false\" aria-controls=\"collapse1\">\r\n");
      out.write("                        <div class=\"nav-link-icon\"><i data-feather=\"activity\"></i></div>\r\n");
      out.write("                        종합랭킹\r\n");
      out.write("                        <div class=\"sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"collapse\" id=\"collapse1\" data-bs-parent=\"#accordionSidenav\">\r\n");
      out.write("                        <nav class=\"sidenav-menu-nested nav accordion\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"\">인기 랭킹</a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"\">인기 랭킹</a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"\">유저 랭킹</a>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"nav-link\" href=\"\">\r\n");
      out.write("                        e스포츠\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"javascript:void(0);\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse2\" aria-expanded=\"false\" aria-controls=\"collapse2\">\r\n");
      out.write("                        <div class=\"nav-link-icon\"><i data-feather=\"activity\"></i></div>\r\n");
      out.write("                        고객센터\r\n");
      out.write("                        <div class=\"sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"collapse\" id=\"collapse2\" data-bs-parent=\"#accordionSidenav\">\r\n");
      out.write("                        <nav class=\"sidenav-menu-nested nav accordion\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"\">사이트소개</a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"notice.jsp\">공지사항</a>\r\n");
      out.write("                            <a class=\"nav-link\" href=\"\">자주묻는질문</a>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(document).on('click', '.menu-toggle', function () {\r\n");
      out.write("        if($(this).hasClass('active')){\r\n");
      out.write("            $('header.navbar').removeClass('active');\r\n");
      out.write("            $(this).removeClass('active');\r\n");
      out.write("            $('.logo').removeClass('off');\r\n");
      out.write("            $('.m-gnb').removeClass('active');\r\n");
      out.write("            $('.gnb-m').removeClass('active');\r\n");
      out.write("        } else {\r\n");
      out.write("            $('header.navbar').addClass('active');\r\n");
      out.write("            $(this).addClass('active');\r\n");
      out.write("            $('.logo').addClass('off');\r\n");
      out.write("            $('.m-gnb').addClass('active');\r\n");
      out.write("            $('.gnb-m').addClass('active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"intro-banner\">\r\n");
      out.write("<div id=\"introBanner\" class=\"carousel slide\" data-bs-ride=\"false\">\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#introBanner\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#introBanner\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#introBanner\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>게임 관련 홍보 배너 1</h5>\r\n");
      out.write("              <p>홍보 설명 입니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>게임 관련 홍보 배너 2</h5>\r\n");
      out.write("              <p>홍보 설명 입니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>게임 관련 홍보 배너 3</h5>\r\n");
      out.write("              <p>홍보 설명 입니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#introBanner\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#introBanner\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("    <script>const carousel = new bootstrap.Carousel('#introBanner')</script>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <div class=\"bg-left\"></div>\r\n");
      out.write("    <div class=\"container position-relative\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- 컨텐츠 화면 -->\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- 공지사항 게시물 리스트 목록 -->\r\n");
      out.write("                    <div class=\"col-xl-6\">\r\n");
      out.write("                        <div class=\"app-notice\">\r\n");
      out.write("                            <h3>공지사항</h3>\r\n");
      out.write("                            <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                            <div class=\"board-list\">\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <colgroup>\r\n");
      out.write("                                        <col class=\"subject\">\r\n");
      out.write("                                        <col class=\"time\">\r\n");
      out.write("                                    </colgroup>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">공지사항 관련 게시글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">공지사항 관련 게시글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">공지사항 관련 게시글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">공지사항 관련 게시글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">공지사항 관련 게시글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 게임 게시물 리스트 목록 -->\r\n");
      out.write("                    <div class=\"col-xl-6\">\r\n");
      out.write("                        <div class=\"app-board\">\r\n");
      out.write("                            <h3>게임 최근게시글</h3>\r\n");
      out.write("                            <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                            <div class=\"board-list\">\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <colgroup>\r\n");
      out.write("                                        <col class=\"subject\">\r\n");
      out.write("                                        <col class=\"time\">\r\n");
      out.write("                                    </colgroup>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">게임 최근글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">게임 최근글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">게임 최근글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">게임 최근글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"subject\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <span class=\"subject\">\r\n");
      out.write("                                            <span class=\"text\">게임 최근글 입니다.</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"time\">\r\n");
      out.write("                                        <time>2023.05.22</time>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 레드앱 등록된 게임 리스트 목록 -->\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"app-game-list\">\r\n");
      out.write("                        <h3>레드앱 등록된 게임 리스트</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                        <ul class=\"app-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple116/v4/51/4c/5f/514c5fd0-0b8e-c049-3ba9-9c991fcd26b0/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">카트라이더 러쉬플러스</span><span class=\"dev\">NEXON Company</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/8a/d0/27/8ad027ee-b093-e152-292c-0e4e766430b1/AppIcon-1x_U007emarketing-0-7-0-85-220.png/217x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">배틀그라운드</span><span class=\"dev\">KRAFTON Inc</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is5-ssl.mzstatic.com/image/thumb/Purple116/v4/d6/4f/04/d64f04be-3293-2488-163f-2d2561e0bb54/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">리그 오브 레전드: 와일드 리프트</span><span class=\"dev\">Riot Games</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/6b/a2/dd/6ba2dd4e-64c5-331c-a245-59ed25a11a7d/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/157x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">Roblox</span><span class=\"dev\">Roblox Corporation</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/e6/b0/3b/e6b03b44-31d3-a25c-4d37-819229958064/AppIcon-0-0-1x_U007emarketing-0-0-0-6-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/157x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">클래시 로얄</span><span class=\"dev\">Supercell</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/f0/b4/16/f0b416b1-3ad0-d034-318b-029a401df49b/AppIcon-1x_U007emarketing-0-7-0-85-220.png/146x0w.webp\"></div>\r\n");
      out.write("                                <div class=\"app-title\"><span class=\"subject\">쿠키런: 킹덤</span><span class=\"dev\">Devsisters</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 데일리 e스포츠 기사 목록 -->\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"app-game-list\">\r\n");
      out.write("                        <h3>국민일보 e스포츠 기사</h3>\r\n");
      out.write("                        <a href=\"https://news.kmib.co.kr/article/list.asp?sid1=spo&sid2=0012\" target=\"_blank\" class=\"more\">더보기</a>\r\n");
      out.write("<style>\r\n");
      out.write(".nws_list {width:100%;padding-bottom:5px;border-bottom:1px solid #c9c9c9;overflow:hidden;}\r\n");
      out.write(".nws_list div.nws {width:100%;margin-bottom:24px;display: table;}\r\n");
      out.write(".nws_list  p.pic {text-align:left;display: table-cell;padding-right:20px;}\r\n");
      out.write(".nws_list  p.pic img {display: block;width:100%;border:1px solid #dadada;}\r\n");
      out.write(".nws_list dl{display: table-cell;vertical-align:top;width: 700px;}\r\n");
      out.write(".nws_list dl dt {text-overflow:ellipsis;white-space:nowrap;overflow:hidden;padding:4px 0 7px 0;}\r\n");
      out.write(".nws_list dl dt a {font-size:17px;font-weight:bold;height:20px;line-height:20px;letter-spacing:-0.07em;}\r\n");
      out.write(".nws_list dl dd.tx {overflow:hidden;font-size: 14px;line-height: 20px;letter-spacing: -0.054em;}\r\n");
      out.write(".nws_list dl dd.tx a {color:#575757;}\r\n");
      out.write(".nws_list dl dd.date {height:18px;padding-top:5px;font-size:12px;color:#acacac}\r\n");
      out.write("</style>\r\n");
      out.write("<?php\r\n");
      out.write("include('simple_html_dom.php');\r\n");
      out.write("\r\n");
      out.write("// 파싱할 웹 사이트의 URL\r\n");
      out.write("$url = 'https://news.kmib.co.kr/article/list.asp?sid1=spo&sid2=0012';\r\n");
      out.write("$html = file_get_html($url);\r\n");
      out.write("$html = $html->find('div[class=\"nws_list\"]', 0);\r\n");
      out.write("$html = preg_replace('/<a href=\"(.*?)\"/', '<a href=\"https://news.kmib.co.kr/article/$1\"', $html);\r\n");
      out.write("echo $html;\r\n");
      out.write("?>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 사이드 화면 -->\r\n");
      out.write("            <side class=\"col-lg-3\">\r\n");
      out.write("                <div class=\"position-sticky\" style=\"top: 85px;\">\r\n");
      out.write("                    <!-- 게임앱 커뮤니티 인기랭킹 TOP 5 목록 -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"app-game-popular-rank\">\r\n");
      out.write("                            <h3>인기 랭킹 TOP 5</h3>\r\n");
      out.write("                            <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                            <ul class=\"rank-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">1<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple116/v4/51/4c/5f/514c5fd0-0b8e-c049-3ba9-9c991fcd26b0/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">카트라이더 러쉬플러스</span><span class=\"dev\">NEXON Company</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">2<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/8a/d0/27/8ad027ee-b093-e152-292c-0e4e766430b1/AppIcon-1x_U007emarketing-0-7-0-85-220.png/217x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">배틀그라운드</span><span class=\"dev\">KRAFTON Inc</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">3<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is5-ssl.mzstatic.com/image/thumb/Purple116/v4/d6/4f/04/d64f04be-3293-2488-163f-2d2561e0bb54/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">리그 오브 레전드: 와일드 리프트</span><span class=\"dev\">Riot Games</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">4<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/e6/b0/3b/e6b03b44-31d3-a25c-4d37-819229958064/AppIcon-0-0-1x_U007emarketing-0-0-0-6-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/157x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">클래시 로얄</span><span class=\"dev\">Supercell</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">5<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/f0/b4/16/f0b416b1-3ad0-d034-318b-029a401df49b/AppIcon-1x_U007emarketing-0-7-0-85-220.png/146x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">쿠키런: 킹덤</span><span class=\"dev\">Devsisters</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 게임앱 커뮤니티 가입랭킹 TOP 5 목록 -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"app-game-join-rank\">\r\n");
      out.write("                            <h3>가입 랭킹 TOP 5</h3>\r\n");
      out.write("                            <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                            <ul class=\"rank-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">1<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/8a/d0/27/8ad027ee-b093-e152-292c-0e4e766430b1/AppIcon-1x_U007emarketing-0-7-0-85-220.png/217x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">배틀그라운드</span><span class=\"dev\">KRAFTON Inc</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">2<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple116/v4/51/4c/5f/514c5fd0-0b8e-c049-3ba9-9c991fcd26b0/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">카트라이더 러쉬플러스</span><span class=\"dev\">NEXON Company</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">3<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is5-ssl.mzstatic.com/image/thumb/Purple116/v4/d6/4f/04/d64f04be-3293-2488-163f-2d2561e0bb54/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/230x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">리그 오브 레전드: 와일드 리프트</span><span class=\"dev\">Riot Games</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">4<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/6b/a2/dd/6ba2dd4e-64c5-331c-a245-59ed25a11a7d/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/157x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">Roblxox</span><span class=\"dev\">Roblox Corporation</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"number\">5<span class=\"d-none\">순위</span></div>\r\n");
      out.write("                                    <div class=\"app-icon\"><img src=\"https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/e6/b0/3b/e6b03b44-31d3-a25c-4d37-819229958064/AppIcon-0-0-1x_U007emarketing-0-0-0-6-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/157x0w.webp\"></div>\r\n");
      out.write("                                    <div class=\"app-title\"><span class=\"subject\">클래시 로얄</span><span class=\"dev\">Supercell</span></div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 관리자 유저 목록 -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"app-admin\">\r\n");
      out.write("                            <h3>관리자 목록</h3>\r\n");
      out.write("                            <a href=\"#\" class=\"more\">더보기</a>\r\n");
      out.write("                            <div class=\"userprofile pf-admin\">\r\n");
      out.write("                                <img src=\"profile.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"userprofile pf-admin\">\r\n");
      out.write("                                <img src=\"profile.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"userprofile pf-admin\">\r\n");
      out.write("                                <img src=\"profile.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"userprofile pf-admin\">\r\n");
      out.write("                                <img src=\"profile.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- footer 하단 화면 -->\r\n");
      out.write("                    <footer class=\"footer col-12\">\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <div class=\"footer-link\">\r\n");
      out.write("                                <a href=\"#\">사이트소개</a>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <a href=\"#\">서비스 약관</a>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <a href=\"#\">개인정보 처리방침</a>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <a href=\"#\">고객센터</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <div class=\"footer-extra\">\r\n");
      out.write("                                <a href=\"https://www.facebook.com/\" target=\"_blank\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("                                <a href=\"https://discord.gg/\" target=\"_blank\"><i class=\"bi bi-discord\"></i></a>\r\n");
      out.write("                                <a href=\"https://twitter.com/\" target=\"_blank\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <cite>RedApp Korea ⓒ 2023</cite>\r\n");
      out.write("                    </footer>\r\n");
      out.write("                </div>\r\n");
      out.write("            </side>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
