/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-06-09 03:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.dw.member.vo.GBookVO;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import kr.or.dw.lounge.vo.LoungeVO;
import java.util.List;
import kr.or.dw.ranking.vo.GameVO;
import kr.or.dw.util.BuildSqlMapClient;
import kr.or.dw.member.vo.MemberVO;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/member/../gnb.jsp", Long.valueOf(1686271655473L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.dw.lounge.vo.LoungeVO");
    _jspx_imports_classes.add("kr.or.dw.member.vo.MemberVO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("kr.or.dw.ranking.vo.GameVO");
    _jspx_imports_classes.add("kr.or.dw.member.vo.GBookVO");
    _jspx_imports_classes.add("kr.or.dw.util.BuildSqlMapClient");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>RedApp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/gnb.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/profile.css\">\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/all.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("// 자바스크립트 & 제이쿼리에서 사용하는 데이터 정보 함수\r\n");
      out.write("// var is_member = '<?php echo isset($is_member)?$is_member:''; ?>';\r\n");
      out.write("// var is_admin  = '<?php echo isset($is_admin)?$is_admin:''; ?>';\r\n");

   String picSrc = "/profilePath/default/defaultProfile.png"; 

   MemberVO memberVo = (MemberVO)request.getAttribute("memberVo");
   if(memberVo.getProfile() != null) {
      picSrc = "/profilePath/" + memberVo.getProfile();
   }
   String userId = memberVo.getId();
   String userNick = memberVo.getNick();
   String userPass = memberVo.getPass();
   String gb_del = memberVo.getGb_del();
   String profile_txt = memberVo.getProfile_txt();
   int u_no = memberVo.getUser_no();
   
   int memberBoardCount = (int)request.getAttribute("memberBoardCount");
   int memberReplyCount = (int)request.getAttribute("memberReplyCount");
   
   List<GameVO> memGameList = (List<GameVO>)request.getAttribute("memGameList");
   
   List<GBookVO> gbList = (List<GBookVO>)request.getAttribute("gbList");
   DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

      out.write('\r');
      out.write('\n');

   if(memberVo.getProfile() == null) {

      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("   $('#deleteBtn').attr('style', 'display: none;');\r\n");
      out.write("})\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("   \r\n");
      out.write("   function imgFilePreview(e) {\r\n");
      out.write("      let reader = new FileReader();\r\n");
      out.write("      \r\n");
      out.write("      reader.onload = function (e) {\r\n");
      out.write("         $('#profile_picture').attr('src', e.target.result);\r\n");
      out.write("      };\r\n");
      out.write("      \r\n");
      out.write("      reader.readAsDataURL(e.target.files[0]);\r\n");
      out.write("      \r\n");
      out.write("      $('#uploadBtn').toggle();     \r\n");
      out.write("   };\r\n");
      out.write("   \r\n");
      out.write("        \r\n");
      out.write("    $('#image').on('change', imgFilePreview);\r\n");
      out.write("   \r\n");
      out.write("    $(\"#uploadBtn\").click(function() {\r\n");
      out.write("          event.preventDefault();\r\n");
      out.write("        var formData = new FormData($('#uploadForm')[0]);\r\n");
      out.write("        \r\n");
      out.write("          $.ajax({\r\n");
      out.write("               url: '");
      out.print( request.getContextPath());
      out.write("/file/ProfilePicture.do?user_no=");
      out.print(u_no);
      out.write("',\r\n");
      out.write("               processData: false,\r\n");
      out.write("               contentType: false,\r\n");
      out.write("               data: formData,\r\n");
      out.write("               dataType : 'json',\r\n");
      out.write("               type: 'POST',\r\n");
      out.write("               success: function(response) {\r\n");
      out.write("                  \r\n");
      out.write("               },\r\n");
      out.write("               error : function(request) {\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("          alert('프로필 사진이 저장 되었습니다.');\r\n");
      out.write("          $('#uploadBtn').toggle();\r\n");
      out.write("          $('#deleteBtn').attr('style', 'display: inline;');\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#deleteBtn\").click(function() {\r\n");
      out.write("          event.preventDefault();\r\n");
      out.write("        var formData = new FormData($('#uploadForm')[0]);\r\n");
      out.write("          $.ajax({\r\n");
      out.write("               url: '");
      out.print( request.getContextPath());
      out.write("/file/deletePicture.do?user_no=");
      out.print(u_no);
      out.write("',\r\n");
      out.write("               processData: false,\r\n");
      out.write("               contentType: false,\r\n");
      out.write("               data: formData,\r\n");
      out.write("               type: 'POST',\r\n");
      out.write("               success: function(response) {\r\n");
      out.write("                   \r\n");
      out.write("               },\r\n");
      out.write("            error : function(request) {\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        $('#image').val('');\r\n");
      out.write("       $('#profile_picture').attr('src', '/profilePath/default/defaultProfile.png');\r\n");
      out.write("       $(\"#deleteBtn\").attr('style', 'display: none;');\r\n");
      out.write("       alert('프로필 사진이 삭제 되었습니다.');\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function gBTemplate(gB){\r\n");
      out.write("        \r\n");
      out.write("        $('#gb_container').prepend(\r\n");
      out.write("          '<div class=\"list\">'   \r\n");
      out.write("                +'   <span class=\"nickname\">'\r\n");
      out.write("                +'      <a href=\"#\">' + gB.nick + '</a>'\r\n");
      out.write("                +'   </span>'\r\n");
      out.write("                +'   <span class=\"time\">' + gB.b_wdt + '</span>'\r\n");
      out.write("                +'   <div class=\"commcont\">' + gB.b_content + '</div>'\r\n");
      out.write("                +' </div>'\r\n");
      out.write("        );\r\n");
      out.write("     };\r\n");
      out.write("     \r\n");
      out.write("     $('#gb_form').on('submit', function(e){\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        let b_content = $('#gb_form').find('#gbbox').val();\r\n");
      out.write("        \r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"");
      out.print(request.getContextPath());
      out.write("/member/gb.do\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           method : \"post\",\r\n");
      out.write("           data : {\r\n");
      out.write("              \"b_content\" : b_content\r\n");
      out.write("           },\r\n");
      out.write("           success : function(res){\r\n");
      out.write("              console.log(res);\r\n");
      out.write("              gBTemplate(res.gB);\r\n");
      out.write("           },\r\n");
      out.write("           error : function(){\r\n");
      out.write("              \r\n");
      out.write("           }\r\n");
      out.write("        });\r\n");
      out.write("        $('#gb_form').find('#gbbox').val(\"\");\r\n");
      out.write("     });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/gnb.css\">\r\n");
      out.write("<!-- 글로벌 네비게이션 바 부분 -->\r\n");
      out.write("<header class=\"gnb\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"logo\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/main.do\"><img src=\"../img/gnb_redapp_logo_v2.png\"></a></div>\r\n");
      out.write("        <div class=\"gnbBarLeft\">\r\n");
      out.write("            <div class=\"gnbAllmenu\">\r\n");
      out.write("                 <a href=\"#gnbAllLayer\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#gnbAllLayer\" aria-controls=\"gnbAllLayer\">\r\n");
      out.write("                    <span class=\"gnbIcon\"></span><span class=\"text\">메뉴</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"gnbBarRight\">\r\n");
      out.write("            <div class=\"member-info\">\r\n");
      out.write("                ");

                	Object user_no = session.getAttribute("user_no");
                	Object auth_cd = session.getAttribute("auth_cd");
                	if(user_no != null){
                
      out.write("\r\n");
      out.write("                <a class=\"btn btn-basic\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">로그아웃</a>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                <a class=\"btn btn-basic\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/loginForm.do\">로그인</a>\r\n");
      out.write("         		");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"offcanvas offcanvas-start gnbAllLayer\" data-bs-scroll=\"true\" tabindex=\"-1\" id=\"gnbAllLayer\" aria-labelledby=\"gnbAllLayerLabel\">\r\n");
      out.write("    <div class=\"gnbTitle\">\r\n");
      out.write("        <h2>Global Navigation Bar</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbLayerBt\">\r\n");
      out.write("        <a href=\"#\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\">\r\n");
      out.write("            <span class=\"gnbIcon\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbMyLayer\">\r\n");
      out.write("        <div class=\"gnbList\">\r\n");
      out.write("            <div class=\"gnbCell\">\r\n");
      out.write("                <h3><a href=\"");
      out.print( request.getContextPath());
      out.write("/main.do\">HOME <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <h3><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=3\">게임 라운지 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=1\">다운랭킹</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ranking/community.do?g=2\">구독랭킹</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"gnbCell\">\r\n");
      out.write("                <h3><a href=\"https://news.kmib.co.kr/article/list.asp?sid1=spo&sid2=0012\">e스포츠 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <h3><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\">고객센터 <i class=\"bi bi-link-45deg\"></i></a></h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:alert('개발 준비중 입니다.','self_close');\">사이트소개</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/faq.do\">자주묻는질문</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gnbListService\">\r\n");
      out.write("        <h2 class=\"d-none\">서비스</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/myinfo.do\"><span></span>내정보</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\"><span></span>고객센터</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/notice.do\"><span></span>공지사항</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/customer/faq.do\"><span></span>자주묻는질문</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a class=\"gnbBtAll\" href=\"");
      out.print( request.getContextPath());
      out.write("/customer/sitemap.do\">전체서비스</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<div class=\"profile-header\">\r\n");
      out.write("    <div class=\"container\" style=\"height: 100%\">\r\n");
      out.write("        <div class=\"profile-info-wrap\">\r\n");
      out.write("            <div class=\"profile-info\">\r\n");
      out.write("                <!-- 프로필 사진 부분 -->\r\n");
      out.write("                <div class=\"profile-image-area\">\r\n");
      out.write("                   \r\n");
      out.write("                    <form id=\"uploadForm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                       <div class=\"style-profile\" style=\"width: 120px; height: 120px;\">\r\n");
      out.write("                          <input type=\"hidden\" name=\"userid\" value=\"");
      out.print( userId );
      out.write("\">\r\n");
      out.write("                              <div class=\"my-profile\">\r\n");
      out.write("                                 <label class=\"label-profile\" for=\"image\">\r\n");
      out.write("                                     <img id=\"profile_picture\" src=\"");
      out.print( picSrc);
      out.write("\" alt=\"user profile picture\">\r\n");
      out.write("                                   ");
if(user_no.equals(u_no)|| auth_cd != null) {
      out.write("\r\n");
      out.write("                                   <input type=\"file\" name=\"image\" id=\"image\" accept=\"image/png, image/jpeg, image/gif, image/jpg\" hidden>\r\n");
      out.write("                                   <input type=\"button\" id=\"uploadBtn\" value=\"업로드하기\" name=\"btn\" style=\"display: none;\">\r\n");
      out.write("                                   <input type=\"button\" id=\"deleteBtn\" value=\"삭제하기\" name=\"btn\" style=\"display: inline;\">\r\n");
      out.write("                                   ");
}
      out.write("\r\n");
      out.write("                                 </label>      \r\n");
      out.write("                              </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 회원 정보 부분 -->\r\n");
      out.write("                <div class=\"profile-name\">\r\n");
      out.write("                    <strong class=\"profile-nickname\">");
      out.print( userNick );
      out.write("</strong>\r\n");
      out.write("                    <div class=\"profile-userid\">@");
      out.print( userId );
      out.write("</div>\r\n");
      out.write("                    ");
if(profile_txt == null) {
      out.write("\r\n");
      out.write("                    <div class=\"profile-introduce\">한줄 자기소개 작성해보세요</div>\r\n");
      out.write("                    ");
} else {
      out.write("\r\n");
      out.write("                    <div class=\"profile-introduce\">");
      out.print( profile_txt);
      out.write("</div>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 프로필 버튼 부분 -->\r\n");
      out.write("            <div class=\"profile-btn\">\r\n");
      out.write("                <button>임시버튼</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"profile-wrapper\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("                <div class=\"side\">\r\n");
      out.write("\r\n");
      out.write("<!--                     <a href=\"#\" class=\"btn btn-activity\"><i class=\"bi bi-journal-check\"></i>나의 활동</a> -->\r\n");
      out.write("\r\n");
      out.write("<!--                     <a href=\"#\" class=\"btn btn-activity\"><i class=\"bi bi-journal-check\"></i>유저 활동</a> -->\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-activity\"><i class=\"bi bi-clipboard-check\"></i>가입 커뮤니티</a>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-activity\"><i class=\"bi bi-calendar-check\"></i>방명록</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"user-activity-wrap\">\r\n");
      out.write("                    <div class=\"user-activity d-flex\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"bi bi-people\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"count_content\">\r\n");
      out.write("                            <h3><span class=\"counter\">0</span> </h3>\r\n");
      out.write("                            <p>구독자</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-activity d-flex\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"bi bi-card-text\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"count_content\">\r\n");
      out.write("                            <h3><span class=\"counter\">");
      out.print(memberBoardCount );
      out.write("</span> </h3>\r\n");
      out.write("                            <p>작성한 글</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user-activity d-flex\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"bi bi-chat-left-dots\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"count_content\">\r\n");
      out.write("                            <h3><span class=\"counter\">");
      out.print(memberReplyCount );
      out.write("</span> </h3>\r\n");
      out.write("                            <p>작성한 댓글</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath());
      out.write("/member/modProfile.do\" method=\"post\">\r\n");
      out.write("                       ");
if(profile_txt == null) {
      out.write("\r\n");
      out.write("                       <input type=\"text\" value=\"한줄 자기소개 작성해보세요\" name=\"profile_txt\">\r\n");
      out.write("                       <input type=\"hidden\" value=\"");
      out.print( u_no );
      out.write("\" name=\"user_no\">\r\n");
      out.write("                       ");
} else {
      out.write("\r\n");
      out.write("                       <input type=\"text\" value=\"");
      out.print( profile_txt);
      out.write("\" name=\"profile_txt\">\r\n");
      out.write("                       <input type=\"hidden\" value=\"");
      out.print( u_no );
      out.write("\" name=\"user_no\">\r\n");
      out.write("                       ");
} 
      out.write("\r\n");
      out.write("                       ");
if(user_no.equals(u_no)|| auth_cd != null) {
      out.write("\r\n");
      out.write("                       <button type=\"submit\">저장하기</button>\r\n");
      out.write("                       ");
} 
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <style>\r\n");
      out.write(".app-game-list {\r\n");
      out.write("    margin: 15px 0;\r\n");
      out.write("}\r\n");
      out.write(".app-game-list:after {\r\n");
      out.write("    display: table;\r\n");
      out.write("    clear: both;\r\n");
      out.write("    content: \" \";\r\n");
      out.write("}\r\n");
      out.write(".app-game-list h4 {\r\n");
      out.write("    font: 1.35rem 'Nanum Gothic';\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".app-game-list .more {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 15px;\r\n");
      out.write("    right: 15px;\r\n");
      out.write("    font: 0.85rem 'Nanum Gothic';\r\n");
      out.write("    color: #8b8b8b;\r\n");
      out.write("}\r\n");
      out.write(".app-list {\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".app-list li {\r\n");
      out.write("    float: left;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: -ms-inline-flexbox;\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    -ms-flex-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    width: 33.33%;\r\n");
      out.write("    margin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("@media(max-width: 991px) {\r\n");
      out.write(".app-list li {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-icon {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-icon:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    border: 1px solid rgba(0,0,0,.06);\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-icon img {\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-title {\r\n");
      out.write("    -ms-flex: 1 1;\r\n");
      out.write("    flex: 1 1;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    margin-left: 14px;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-title .subject {\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -ms-flex-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    line-height: 19px;\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write(".app-list li .app-title .dev {\r\n");
      out.write("    margin-top: 3px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    line-height: 15px;\r\n");
      out.write("    max-height: 15px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    -webkit-line-clamp: 1;\r\n");
      out.write("    -webkit-box-orient: vertical;\r\n");
      out.write("}\r\n");
      out.write("                    </style>\r\n");
      out.write("                     <div class=\"app-game-list\" >\r\n");
      out.write("                        <h4>가입 커뮤니티</h4>\r\n");
      out.write("                        <ul class=\"app-list\">\r\n");
      out.write("                         ");

                            for(GameVO game : memGameList){
                         
      out.write(" \r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"app-icon\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/lounge/gameLounge.do?g_no=");
      out.print( game.getG_no());
      out.write("'\"><img src=\"/imgPath/");
      out.print( game.getG_no());
      out.write("-icon.png\"></div>\r\n");
      out.write("                                <div class=\"app-title\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/lounge/gameLounge.do?g_no=");
      out.print( game.getG_no());
      out.write("'\"><span class=\"subject\">");
      out.print(game.getG_name());
      out.write(" </span><span class=\"dev\">");
      out.print(game.getG_com() );
      out.write("</span></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                         ");

                             }
                         
      out.write(" \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <style>\r\n");
      out.write("            .bottom_txar_wrap {\r\n");
      out.write("             height: 170px;\r\n");
      out.write("             background-color: #e8eaee;\r\n");
      out.write("             border: 1px solid #dcdde1;\r\n");
      out.write("         }\r\n");
      out.write("            .bottom_txar_wrap .txar {\r\n");
      out.write("             float: left;\r\n");
      out.write("             padding: 20px;\r\n");
      out.write("             width: calc(100% - 20px);\r\n");
      out.write("             height: 90px;\r\n");
      out.write("             margin-top: 10px;\r\n");
      out.write("             margin-left: 10px;\r\n");
      out.write("             background-color: #fff;\r\n");
      out.write("             resize: none;\r\n");
      out.write("             overflow: hidden;\r\n");
      out.write("             overflow-y: auto;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn {\r\n");
      out.write("             position: relative;\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-top: 11px;\r\n");
      out.write("             width: 100%;\r\n");
      out.write("             height: 42px;\r\n");
      out.write("             line-height: 42px;\r\n");
      out.write("             padding: 0 10px;\r\n");
      out.write("         }\r\n");
      out.write("         .glist_number {\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-right: 20px;\r\n");
      out.write("             font-size: 14px !important;\r\n");
      out.write("             color: #666666;\r\n");
      out.write("             margin-right: 10px;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn span {\r\n");
      out.write("             float: left;\r\n");
      out.write("             margin-right: 0px;\r\n");
      out.write("             font-size: 12px;\r\n");
      out.write("             color: #666666;\r\n");
      out.write("         }\r\n");
      out.write("         .bottom_txar_btn span .btn-write {\r\n");
      out.write("             width: 100%;\r\n");
      out.write("             background: #d63338;\r\n");
      out.write("             color: #fff;\r\n");
      out.write("             padding: 7px 5px;\r\n");
      out.write("             border-radius: 0;\r\n");
      out.write("         }\r\n");
      out.write("            </style>\r\n");
      out.write("                  <div class=\"bottom_txar_wrap\" style=\"\">\r\n");
      out.write("                   <form id=\"gb_form\">\r\n");
      out.write("                   <textarea id=\"gbbox\" name=\"gbook\" cols=\"30\" rows=\"10\" class=\"txar\" placeholder=\"댓글을 입력하세요.\"></textarea>\r\n");
      out.write("                   <div class=\"bottom_txar_btn\">\r\n");
      out.write("                       <div class=\"float-end text-end\">\r\n");
      out.write("                           <div class=\"glist_number\">(<em id=\"count\">0</em>/200)</div>\r\n");
      out.write("                           <span><button type=\"submit\" class=\"btn btn-write\" >방명록등록</button></span>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                  </form>   \r\n");
      out.write("                  </div>\r\n");
      out.write("                    <style>\r\n");
      out.write("            .comment {\r\n");
      out.write("               width: 100%;\r\n");
      out.write("               padding: 15px 0;\r\n");
      out.write("               border-top: 2px solid #333;\r\n");
      out.write("            }\r\n");
      out.write("            .comment a {\r\n");
      out.write("               text-decoration: none;\r\n");
      out.write("               color: #333;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list {\r\n");
      out.write("               padding:15px 0;\r\n");
      out.write("               border-bottom: 1px solid #eee;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .nickname {\r\n");
      out.write("               font-size:1.05rem;\r\n");
      out.write("               font-weight: 700;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .time {\r\n");
      out.write("               font-size:0.95rem;\r\n");
      out.write("               font-weight: normal;\r\n");
      out.write("               margin-left: 5px;\r\n");
      out.write("               letter-spacing: -0.05em;\r\n");
      out.write("            }\r\n");
      out.write("            .comment .list .commcont {\r\n");
      out.write("               margin: 5px 0 0;\r\n");
      out.write("               font-size: 0.85rem;\r\n");
      out.write("            }\r\n");
      out.write("            </style>\r\n");
      out.write("                    <div class=\"comment\" id=\"gb_container\">\r\n");
      out.write("                 ");
 
                         for(GBookVO gBVo : gbList){
                   
      out.write(" \r\n");
      out.write("                      <div class=\"list\">   \r\n");
      out.write("                         <span class=\"nickname\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/userInfo.do?user_no=");
      out.print( memberVo.getUser_no());
      out.write('"');
      out.write('>');
      out.print( gBVo.getNick() );
      out.write("</a> \r\n");
      out.write("                         </span> \r\n");
      out.write("                         <span class=\"time\"> ");
      out.print( formatter.format(gBVo.getB_wdt()));
      out.write("</span> \r\n");
      out.write("                         <div class=\"commcont\">");
      out.print( gBVo.getB_content() );
      out.write(" </div> \r\n");
      out.write("                      </div>\r\n");
      out.write("                   ");
 
                         }
                   
      out.write(" \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
